export const metadata = {
    title: "Wareact - Insight",
    description: "Generated by Wareact",
     icons: {
      icon: "/icons/signup/logo.svg"
    },
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
  <>
    {children}
  </>
    )
  }
  