import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/header/page";
import Footer from "@/components/footer/page";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Wareact - 3PL Warehouse Software",
  description: "Generated by Wareact",
   icons: {
    icon: "/icons/signup/logo.svg"
  },

openGraph: {
    type: "website",
    url: "https://www.wareact.com",
    title: "Wareact - 3PL Warehouse Software",
    description:
      "Built for 3PL warehouses, our software automates everything from inventory tracking to billing—helping you deliver faster, smarter, and more accurate fulfillment.",
    images: [
      {
     
        url: "/og/log.png?v=1",
        width: 1200,
        height: 630,
        alt: "Wareact – 3PL Warehouse Software",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Wareact - 3PL Warehouse Software",
    description:
      "Built for 3PL warehouses, our software automates everything from inventory tracking to billing—helping you deliver faster, smarter, and more accurate fulfillment.",
    images: ["/og/log.png?v=1"],
  },
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
