import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Wareact - Sign Up",
  description: "Generated by Wareact",
   icons: {
    icon: "/icons/signup/logo.svg"
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
